---
title: "Step 2.5 aggregate to hour"
output: html_document
date: "2023-01-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Input :  The cleaned manual acoustic analysis data from the Marker 2020 study 

# Outputs: 1. All bat activity aggregated to hour per site
           

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
knitr::opts_chunk$set(tidy = "styler")
options(knitr.table.format = "html")

# set project working directory according to the user system info 
# Otherwise, all the data (inputs and outputs, including figures) can be stored on a shared OneDrive folder

user <- Sys.info()['effective_user'] 
user
# this should print your nmbu user name - "apmc" in my case. 

wd <- getwd()
wd
# "C:/Users/apmc/OneDrive - Norwegian University of Life Sciences/Documents/1. PhD_Main/GitHub_link/MarkerBatAcousticAnalyses/MarkerBatAcousticAnalyses2022"


##########################################################
#### Work environment set up ####
##########################################################

library(knitr)
library(data.table)
library(tidyverse)
library(beepr)
library(lubridate)
library(purrr)
#renv::install("rstudio/renv")
library(renv)
library(stringr)
library(janitor)
library(anytime)
library(kableExtra)
library(papeR)
library(skimr)
library(vtable)
library(suncalc)

##########################################################
#### Import data  ####
##########################################################

# All input data can be found on a shared OneDrive folder - we can both share the same input folder but we should have different Output folders. 

# for Katrine 
#input <- ""

# for Reed 
input <- "C:/Users/April/Desktop/WorkBay1/Marker/Inputs"

dataset1 <- "MarkerManual_cleaned_manualid_guild_sitenames.csv"
dataset2 <- "Marker_night_inventory_0704.2022_edit (1).csv"
dataset3 <- "TRUE_hourlyaverageweather_wholepark (1).csv"

path1 <- str_c(input, "/", dataset1)
path2 <- str_c(input, "/", dataset2)
path3 <- str_c(input, "/", dataset3)

bats1. <- read_csv(path1) # 19438 bat passes with 22 vars
active.nights <- read.csv(path2, sep = ";") # # 951 obs of 3 variables
weather.hours <- read_csv(path3) # 93 obs of 8 vars


# for Reed
output <- "C:/Users/April/Desktop/WorkBay1/Marker/Outputs"

# for Katrine 
#output <- ""

## 
 file.name <- "Step2.5 Marker aggregated to hour"
# 
 todays_date <- Sys.Date()
# 
dir.name <- str_c(output,"/", file.name, "_", todays_date)
 dir.name
# 
 dir.create(dir.name) # be careful not to run over an already created directory 

output_today <- dir.name

setwd(output_today)

getwd()
# "C:/Users/April/Desktop/WorkBay1/Marker/Outputs/Step2.5 Marker aggregated to hour_(today's date)"
```

# Make some pretty tables with the unaggregated dataset 
```{r}
# make factor levels arranged in orders that are more meaningful and insert a taxa column with more specific manual id names. 

names(bats1.)
cols <- c("manual.id" ,  "behavior"  ,  "guild"     ,  
          "Site"     ,   "Habitat"   ,  "Locality"  ,  "Facility")
bats1.[cols] <- lapply(bats1.[cols], factor)
bats1.$taxa <- bats1.$manual.id
levels(bats1.$taxa)
# "BABA" "EPNI" "LR1"  "LR2"  "MR1"  "NYNO" "NoID" "PAUR" "PINA" "PIPY" "SR1"  "VEMU"
levels(bats1.$taxa) <- list("Barbastella barbastellus" = "BABA",
                           "Plecotus auritus" = "PAUR",
                           "Short range group 1" = "SR1",
                           "Eptesicus nilssonii" = "EPNI",
                           "Nyctalus noctula" = "NYNO",
                           "Vespertilio murinus" = "VEMU",
                           "Long range group 1" = "LR1",
                           "Long range group 2" = "LR2",
                           "Medium range group1" = "MR1",
                           "Pipistrellus nathusii" = "PINA",
                           "Pipistrellus pygmaeus" = "PIPY",
                            "Unknown bat" = "NoID") 
summary(bats1.$taxa)

levels(bats1.$guild) <- list("SRE" = "SRE", "MRE" = "MRE", "LRE" = "LRE", "NoID" = "NoID")
summary(bats1.$guild)

levels(bats1.$Locality)
levels(bats1.$Locality) <-list("Turbine2" = "Turbine2" , "Turbine4" = "Turbine4",  "Turbine8" = "Turbine8", "MeteorologicalTower" = "MeteorologicalTower", "Turbine9" = "Turbine9", "Turbine10" = "Turbine10", "Turbine11" = "Turbine11", "Turbine14" = "Turbine14") 
summary(bats1.$Locality)

# Can play with these and make them much nicer... 
kbl(summarize(bats1., type = "factor", variables = "manual.id"))  %>%  kable_styling()
kbl(summarize(bats1., type = "factor", variables = "taxa"))  %>%  kable_styling()
kbl(summarize(bats1., type = "factor", variables = "guild"))  %>%  kable_styling()
kbl(summarize(bats1., type = "factor", variables = "Site"))  %>%  kable_styling()
kbl(summarize(bats1., type = "factor", variables = "Habitat"))  %>%  kable_styling()
kbl(summarize(bats1., type = "factor", variables = "Facility"))  %>%  kable_styling()

names(bats1.)
bats2. <- bats1. %>% select(HOUR.12, HOUR, DATE, DATE.12, behavior, guild, Site, Habitat, Locality, Facility, taxa) 

st(bats2.) # summary table of all the relevant factor levels across the whole dataset

# export the html file: 

#st(bats2., file = file.path(output_today, "total summary table"))


```


1. all bat activity aggregated to hour per site
- Insert zeros
- merge with night aggregated weather data 
```{r}

# create night-hour column
bats1.$nighthour <- paste(bats1.$DATE.12, " ",bats1.$HOUR.12, ":00", sep= "")
bats1.$datehour <- paste(bats1.$DATE, " ",bats1.$HOUR, ":00", sep= "")
bats3. <- bats1. %>% mutate(date = as.Date(DATE),
                           night = as.Date(DATE.12),
                           nighthour = ymd_hm(nighthour),
                           datehour = ymd_hm(datehour))   

# make locations maps 
bat_sitemap <- bats1. %>% select(Site, Habitat, Facility, Locality) %>% distinct() 

bats_hours_sum <- bats3. %>% group_by(Site, datehour) %>% dplyr::summarize(batpass = sum(n())) 
bats_hours_sum1 <- left_join(bats_hours_sum, bat_sitemap)
summary(bats_hours_sum1)
summary(bats_hours_sum1$Site)
dat <- bats_hours_sum1 %>% mutate(date = as.Date(datehour)) 
summary(dat)
summary(dat$Site)

timemap <- bats1. %>% select(Site, datehour, nighthour, DATE, DATE.12, HOUR, HOUR.12) %>% distinct() # you will want this later... 
timemap$datehour <- ymd_hm(timemap$datehour)
timemap$nighthour <- ymd_hm(timemap$nighthour)

## The number of hours with recorded bat passes per site 
# Met45 Met95   N02   N04   N08   N09   N10   N11   N14   P02   P04   P08   P09   P10   P11   P14 
#  127    24   221   157   199   232   259   192   235   203   187   166   257   245   259   219 

#write.csv(bats_nights_sum1, "bat pass aggregated by night wout zeronights.csv")

################################################
# Insert zero activity nights
################################################
head(active.nights)

active.nights$Site <- gsub("C", "N", active.nights$Site)
active.nights$Site <- gsub("MetA", "Met45", active.nights$Site)
active.nights$Site <- gsub("MetB", "Met95", active.nights$Site)
active.nights$Site <- as.factor(active.nights$Site)
active.nights$night <- as.Date(active.nights$night, '%d.%m.%Y')
active.nights$night <- as.Date(active.nights$night)
summary(active.nights)

#---- ADDING MISSING DAYS AND HOURS

# adjust dataset to include nights when detectors were active but no data was collected. 

head(active.nights)
summary(active.nights$Site)

nights <- unique(active.nights$night) # 91 unique nights of survey


# restrict to only between one hour before sunset and one hour after sunrise 
## Recalculate day_length 

# manually add 09.30 
thenights <- as.data.frame(active.nights$night %>% unique())
colnames(thenights)[1] = "date"
day0930 <- as.data.frame(as.Date("2020-09-30")) 
colnames(day0930 )[1] = "date"
thenights1 <- full_join(thenights, day0930)
# Will have to use night as a proxy for date


#Use location of T-08
photoperiod <- getSunlightTimes(
  date = thenights1$date, 
  keep = c("sunrise", "sunset"),
  lat = 59.49964,
  lon = 11.73199, 
  tz = "CET")

photoperiod1 <- photoperiod %>%
  mutate(
    date = as.POSIXct(date),
    day_length = as.numeric(sunset - sunrise)) %>% distinct()

photoperiod2 <- photoperiod1 %>% mutate(night = as.Date(date)) %>% select(-date) %>% distinct()
summary(photoperiod2)
#write.csv(photoperiod2, "day_length for active.nights Marker2020.csv")

 str(photoperiod1)
#  $ date      : POSIXct, format: "2020-07-01 02:00:00" "2020-07-02 02:00:00" "2020-07-03 02:00:00" "2020-07-04 02:00:00" ...
#  $ lat       : num  59.5 59.5 59.5 59.5 59.5 ...
#  $ lon       : num  11.7 11.7 11.7 11.7 11.7 ...
#  $ sunrise   : POSIXct, format: "2020-07-01 04:02:08" "2020-07-02 04:03:13" "2020-07-03 04:04:22" "2020-07-04 04:05:35" ...
#  $ sunset    : POSIXct, format: "2020-07-01 22:34:05" "2020-07-02 22:33:22" "2020-07-03 22:32:34" "2020-07-04 22:31:41" ...
#  $ day_length: num  18.5 18.5 18.5 18.4 18.4 ...
# 

# Calculate the active hours for each site 
# Make 24 hours for each active.night

hours.expand <- expand.grid(night = active.nights$night, hour = sprintf("%02d:00", 0:23)) 
active.nights1 <- active.nights %>% select(c(Site, night)) 
hours.expand1 <- left_join(active.nights, hours.expand, by = "night") %>% distinct() 
hours.expand1$nighthour <- paste(hours.expand1$night, hours.expand1$hour)
hours.expand1$nighthour <- ymd_hm(hours.expand1$nighthour)
hours.expand2 <- hours.expand1 %>% select(Site, nighthour) %>% distinct()

# 22824 obs = 951 detector nights * 24 hours - good! 
str(hours.expand2)

#write.csv(hours.expand1, "24active.nighthours.Marker2020.csv")

# merge the bats dataset to with the photoperiod dataset 
photoperiod1$date <- as.Date(photoperiod1$date)
dat1 <- left_join(dat, timemap) %>% select(-c(Habitat, Locality, Facility, datehour, date, DATE, DATE.12, HOUR, HOUR.12)) %>% distinct()
summary(dat1)
str(dat1)
str(hours.expand2)

dat2 <- merge(dat1, hours.expand2, all.y = TRUE) %>% distinct()
summary(dat2) # 19642  NAs introduced 
#22824 obs 

dat3 <- dat2 %>% mutate_at(3, ~replace_na(.,0))  
sum(dat3$batpass) # 19438 - good! 

# add back date and datehour then photoperiods/sunset data
dat4 <- dat3 %>% mutate(datehour = nighthour + 12*60*60,
                        date = as.Date(datehour))

dat5 <- left_join(dat4, photoperiod1) %>% distinct()

dat6 <- dat5 %>% mutate(starttime = sunset - hours(3), endtime = sunrise + hours(3)) 
summary(dat6) 

dat7<- dat6%>%  
  mutate(Keep = case_when(
  datehour >= starttime | datehour <= endtime ~ "Yes", TRUE ~ "No"
))

dat7$Keep <- as.factor(dat7$Keep)
summary(dat7) # 8981 observations that do not fit. 

#Do any have bat passes? 
test <- dat7 %>% filter(Keep == "No")
sum(test$batpass) 
# would lose 17 bat passes if I kept the cut off at 2 hours... 
# 3 hours gives us more zeros but keeps all bat passes.

dat8<- dat7 %>% filter(Keep == "Yes") %>% select(-c(Keep)) %>% droplevels() 
summary(dat8)

# 13843 detector hours for total bat passes 

#write.csv(dat8, "hourlyaggregatedMarker2020_totalbats_zeroinserted.csv") 

## Add back location information and julian night 

dat9 <- left_join(dat8, bat_sitemap)
summary(dat9)
dat9$night <- as.Date(dat9$nighthour)
dat9$jnight <- yday(dat9$night)

```

# Aggregate the hourly weather datasets to nightly 
```{r}
head(weather.hours)

dat10 <- left_join(dat9, weather.hours, by = "nighthour") %>% select(- ...1)

summary(dat10)

sum(dat10$batpass) # 19438
# 40 NA observations added - only one bat pass in all of these included hours with bat passes (1 pass from N08)
# These are time slots when no weather data is available for inserted zero hours at a handful of sites. 
# I will drop these

dat11 <- drop_na(dat10) 
summary(dat11) # 13803 observations
sum(dat11$batpass) # 19437
#write.csv(dat11, "hourlaggregated_totalbats_zeroinserted_weather_jnight_localitiesadded.csv")
```


